ai_context_version: 1.0

project:
  name: wgx
  summary: CLI orchestrator for dev/ops tasks and multi-agent flows.
  role: tooling_orchestration
  primary_language: bash
  visibility: internal

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - validation_hooks
    - name: chronik
      relationship: uses
      interface:
        - ci_e2e_orchestration
  external:
    - name: jq
    - name: curl

architecture:
  entrypoints:
    - wgx/cmd/*
  key_paths:
    - path: modules/
      purpose: subcommand implementations
  data_flow:
    input: developer commands
    processing: fan-out to repos
    output: reports/metrics

conventions:
  branching: "main, feature/*"
  commit_prefix: "wgx"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - compose subcommands; avoid global mutable state
  dont:
    - hardcode repo-specific paths in core modules
