name: Run Bats test suite
description: |
  Run the repository's Bats-based test suites.
  
  Prerequisites:
  - Python 3 must be set up via actions/setup-python@v5 before calling this action.
  - This is required for heimgeist test fixtures and JSON validation.
inputs:
  working-directory:
    description: Directory to run bats from
    required: false
    default: .
  bats-args:
    description: "Arguments to pass to the bats command (for example: \"-r tests\")"
    required: false
    default: -r tests
runs:
  using: composite
  steps:
    - name: Ensure bats and other dependencies are available
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends python3 python3-venv bats jq python3-yaml
        # Verify Python 3 is working correctly
        python3 --version
        python3 -c "import json, sys, os" || {
          echo "::error::Python3 installation verification failed"
          exit 1
        }
        # Install jsonschema for heimgeist insight validation
        # Note: Python 3 must be set up via actions/setup-python@v5 before calling this action
        python3 -m pip install jsonschema
    - name: Install bats helpers
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        mkdir -p test
        if [ ! -d test/bats-support ]; then
          git clone https://github.com/bats-core/bats-support.git test/bats-support
          (cd test/bats-support && git checkout v0.3.0)
        fi
        if [ ! -d test/bats-assert ]; then
          git clone https://github.com/bats-core/bats-assert.git test/bats-assert
          (cd test/bats-assert && git checkout v2.0.0)
        fi
    - name: Execute bats
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        BATS_ARGS: ${{ inputs.bats-args }}
        # DRY_RUN: Set to 'true' to enable dry-run mode in scripts that support it. Expected values: 'true' or '' (default: ''). Currently not used by this workflow, but available for downstream scripts.
        DRY_RUN: ''
      run: |
        set -euo pipefail
        if [ -n "$BATS_ARGS" ]; then
          # Use eval and set -- to properly handle quoted arguments.
          eval "set -- $BATS_ARGS"
          _bats_args=("$@")
        else
          _bats_args=()
        fi
        bats "${_bats_args[@]}"
