---
name: repository-verification

"on":
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  guard:
    uses: heimgewebe/metarepo/.github/workflows/reusable-repo-verify.yml@5afd566efb27fb6594ff32daa4d3b86c5184ba30
    with:
      mode: guard
    permissions:
      contents: read

  smoke:
    uses: heimgewebe/metarepo/.github/workflows/reusable-repo-verify.yml@5afd566efb27fb6594ff32daa4d3b86c5184ba30
    with:
      mode: smoke
    permissions:
      contents: read
