---
name: wgx-guard

"on":
  push:
    branches: [main]
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  guard:
    uses: heimgewebe/metarepo/.github/workflows/reusable-repo-verify.yml@31dbecc6c7b966faa73ad3dceb0ded7329187f36
    with:
      mode: guard
    permissions:
      contents: read
