---
name: wgx-smoke

"on":
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    uses: heimgewebe/metarepo/.github/workflows/reusable-repo-verify.yml@31dbecc6c7b966faa73ad3dceb0ded7329187f36
    with:
      mode: smoke
    permissions:
      contents: read
