---
name: wgx-smoke

"on":
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    uses: heimgewebe/metarepo/.github/workflows/reusable-repo-verify.yml@fe6950616b2d06343e284a56a8944e0a36f1f972
    with:
      mode: smoke
    permissions:
      contents: read
